### ISSUE TITLE
Is there any example code , how to use ngAnimate with angular-toastr?

### ISSUE THREAD

**Issue by beebase** [Foxandxss/angular-toastr#119]

**Comment by Foxandxss** [comment]
Just add `angular-animate.js` to your app and load it as a dependency. That will make the toasts to animate.

**Comment by beebase** [comment]
Actually I was looking for a way to override the default fading with something else from animate.css. 
I found the ngAnimate triggers in angular-toastr.css and created a custom.css override with
```css
.toast.ng-enter {
  animation : fadeInLeft 0.5s;
}
.toast.ng-leave {
  animation : fadeOutLeft 0.5s;
}
```

Seems to work fine.
Thanks.
